version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      - REACT_APP_SERVER_URL=http://backend:3001
    depends_on:
      - backend

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - MONGO_URI=mongodb://mongo:27017/cinelove
      - PORT=3001
      - CLIENT_URL=http://localhost:3000
      - FIREBASE_SERVICE_ACCOUNT_PATH=/app/serviceAccount.json
    volumes:
      - ./server/serviceAccount.json:/app/serviceAccount.json
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: