name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      - name: Install Dependencies
        run: npm ci
      - name: Run Frontend Tests
        run: npm test -- --coverage
      - name: Upload Coverage
        uses: actions/upload-artifact@v3
        with:
          name: frontend-coverage
          path: coverage/

  test-backend:
    runs-on: ubuntu-latest
    services:
      mongo:
        image: mongo:latest
        ports:
          - 27017:27017
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      - name: Install Server Dependencies
        working-directory: ./server
        run: npm ci
      - name: Run Backend Tests
        working-directory: ./server
        env:
          MONGO_URI: mongodb://localhost:27017/cinelove_test
        run: npm test -- --coverage
      - name: Upload Coverage
        uses: actions/upload-artifact@v3
        with:
          name: backend-coverage
          path: server/coverage/

  build:
    runs-on: ubuntu-latest
    needs: [test-frontend, test-backend]
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      - name: Install Frontend Dependencies
        run: npm ci
      - name: Build Frontend
        run: npm run build
      - name: Install Server Dependencies
        working-directory: ./server
        run: npm ci
      - name: Archive Build
        uses: actions/upload-artifact@v3
        with:
          name: frontend-build
          path: build/