name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    needs: [test-frontend, test-backend, build]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and Push Frontend Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/cinelove-frontend:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/cinelove-frontend:latest
      - name: Build and Push Backend Image
        working-directory: ./server
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/cinelove-backend:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/cinelove-backend:latest

dependencies:
  test-frontend:
    uses: ./.github/workflows/ci.yml
  test-backend:
    uses: ./.github/workflows/ci.yml
  build:
    uses: ./.github/workflows/ci.yml